package javase.day8.test.exception;

/**
 * @ClassName ExceptionDemo
 * @Description Exception异常学习，要处理的是非运行异常
 * @Author Cunhao Fan
 * @Date 2023/4/15 9:01
 * @Version 1.0
 */
public class ExceptionDemo {
    public static void main(String[] args) {
        /*try{有可能发生异常的代码块，遇到异常将异常交给catch中的异常对象（传给异常参数）} catch(异常类型 异常参数){异常参数.pritstackTrace  打印错误信息}*/

    }
}
